### ISSUE TITLE
Sentence Option

### ISSUE THREAD

**Issue by ausgerechnet** [tsproisl/SoMeWeTa#12]
When using SoMeWeTa in a pipeline with SoMaJo, a respective 'sentence-tag' option would come in handy. Right now,

`less some-file.xml.gz | somajo-tokenizer --xml --split_sentences --sentence_tag s --tag p --parallel 4 - | somewe-tagger --xml --parallel 4 --tag german_web_social_media_2020-05-28.model -
`

does not work since SoMeWeTa expects newlines as sentence breaks.

This can be fixed on the fly with something like

`
less some-file.xml.gz | somajo-tokenizer --xml --split_sentences --sentence_tag s --tag p --parallel 4 - | sed 's|</s>|</s>\n|' - | somewe-tagger --xml --parallel 4 --tag german_web_social_media_2020-05-28.model - 
`

but this is rather hacky …

Please enhance this amazing tool!

**Comment by tsproisl** [comment]
I've actually missed that option myself on a couple of occasions. So here it is!

**Comment by ausgerechnet** [comment]
works like a charm, thanks!

`somajo-tokenizer --xml --split_sentences --sentence-tag s --tag p --parallel 4 some-file.xml | somewe-tagger --xml --sentence-tag s --parallel 4 --tag some.model -`
