### ISSUE TITLE
Jupyter Notebook: Future Warning possible nested set

### ISSUE THREAD

**Issue by vizzerdrix55** [tsproisl/SoMeWeTa#3]
I use SoMeWeTa in Jupyter Notebook 5.7.4 with Python 3.7.1. I Installed SoMeWeTa in Jupyter Notebook using
```
import sys
!{sys.executable} -m pip install -U SoMeWeTa
```
When I try to run the following test code I found under [Using the Module](https://github.com/tsproisl/SoMeWeTa#using-the-module)
```
from someweta import ASPTagger

model = "german_web_social_media_2018-12-21.model"
sentences = [["Ein", "Satz", "ist", "eine", "Liste", "von", "Tokens", "."],
             ["Zeitfliegen", "mögen", "einen", "Pfeil", "."]]

# future versions will have sensible default values
asptagger = ASPTagger(beam_size=5, iterations=10)
asptagger.load(model)
```
The output contains multiple errors that look like this:

> /anaconda3/lib/python3.7/site-packages/someweta/tagger.py:30: FutureWarning: Possible nested set at position 2
>   self.email = re.compile(r"^[[:alnum:].%+-]+(?:@| \[?at\]? )[[:alnum:].-]+(?:\.| \[?dot\]? )[[:alpha:]]{2,}$", re.IGNORECASE)
> /anaconda3/lib/python3.7/site-packages/someweta/tagger.py:30: FutureWarning: Possible nested set at position 34
>   self.email = re.compile(r"^[[:alnum:].%+-]+(?:@| \[?at\]? )[[:alnum:].-]+(?:\.| \[?dot\]? )[[:alpha:]]{2,}$", re.IGNORECASE)
> /anaconda3/lib/python3.7/site-packages/someweta/tagger.py:30: FutureWarning: Possible nested set at position 66
>   self.email = re.compile(r"^[[:alnum:].%+-]+(?:@| \[?at\]? )[[:alnum:].-]+(?:\.| \[?dot\]? )[[:alpha:]]{2,}$", re.IGNORECASE)

Actually, everything seems to work correctly: I tested the following code:
```
for sentence in sentences:
    tagged_sentence = asptagger.tag_sentence(sentence)
    print("\n".join(["\t".join(t) for t in tagged_sentence]), "\n", sep="")
```
which gave the following correct output:

> Ein	ART
> Satz	NN
> ist	VAFIN
> eine	ART
> Liste	NN
> von	APPR
> Tokens	NN
> .	$.
> 
> Zeitfliegen	NN
> mögen	VMFIN
> einen	ART
> Pfeil	NN
> .	$.

It might be useful for other users to fix this (maybe with adding an explicit installation guide for Jupyter Notebook)

**Comment by tsproisl** [comment]
Thank you for pointing that out! Fixed in version 1.5.1.
